azure:
  free_disk_space: true
github:
  branch_name: main
  tooling_branch_name: main
conda_forge_output_validation: true
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_install_tool: pixi
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
